# Generated by Django 3.2.8 on 2023-12-11 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TipoSolicitud', models.CharField(choices=[['Eventos', 'Eventos'], ['Programas educativos', 'Programas educativos'], ['Deportes', 'Deportes'], ['Concursos', 'Concursos'], ['Comités de vecinos', 'Comités de vecinos'], ['Otros', 'Otros']], max_length=100, verbose_name='Tipo de Actividad')),
                ('Descripcion', models.TextField(verbose_name='Descripcion')),
                ('Imagen', models.ImageField(upload_to='images/actividades/', verbose_name='Imagen')),
                ('fecha_actividad', models.DateField(verbose_name='Fecha de actividad')),
                ('estado', models.CharField(choices=[['R', 'Registro'], ['D', 'Desarrollo'], ['F', 'Finalizado']], default='R', max_length=1, verbose_name='Estado')),
                ('cupos', models.PositiveIntegerField(default=0, verbose_name='Cupos de inscripcion')),
                ('encargado', models.ForeignKey(limit_choices_to={'groups__name': 'directiva'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado de la actividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=100, verbose_name='Nombre del Documento')),
                ('tipo_documento', models.CharField(choices=[('Certificado de residencia', 'Certificado de residencia'), ('Boleta', 'Boleta')], max_length=50, verbose_name='Tipo de Documento')),
                ('fecha_publicacion', models.DateTimeField(editable=False, verbose_name='Fecha de Publicación')),
                ('descripcion_documento', models.TextField(verbose_name='Descripción del Documento')),
                ('archivo', models.FileField(upload_to='documentos/', verbose_name='Adjunta un documento que compruebe tu identidad.')),
                ('estado', models.CharField(blank=True, choices=[['A', 'Aprobado'], ['R', 'Rechazado'], ['P', 'En progreso']], default='P', max_length=1, null=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TipoSolicitud', models.CharField(choices=[[0, 'Seguridad'], [1, 'Mejora de calles'], [2, 'Eventos'], [3, 'Mejoras de infraestructura'], [4, 'Concursos'], [5, 'Otros']], max_length=100, verbose_name='Tipo de propuesta')),
                ('Descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TipoProyecto', models.CharField(choices=[['Seguridad', 'Seguridad'], ['Programas educativos', 'Programas educativos'], ['Eventos', 'Eventos'], ['Mejoras de infraestructura', 'Mejoras de infraestructura'], ['Comités de vecinos', 'Comités de vecinos'], ['Otros', 'Otros']], max_length=100, verbose_name='Tipo de proyecto')),
                ('Descripcion', models.TextField(verbose_name='Descripcion')),
                ('Imagen', models.ImageField(upload_to='images/proyectos/', verbose_name='Imagen')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de proyecto')),
                ('encargado', models.ForeignKey(blank=True, limit_choices_to={'groups__name__in': ['directiva', 'presidente']}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado de la actividad')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='RegistroProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Vecino regular')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntavecinos.proyectos', verbose_name='Proyectos')),
                ('vecino', models.ForeignKey(limit_choices_to={'groups__name': 'usuario'}, on_delete=django.db.models.deletion.CASCADE, related_name='vecinos_registrations_proyectos', to=settings.AUTH_USER_MODEL, verbose_name='Vecino')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='RegistroActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Vecino regular')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntavecinos.actividades', verbose_name='Actividades')),
                ('vecino', models.ForeignKey(limit_choices_to={'groups__name': 'usuario'}, on_delete=django.db.models.deletion.CASCADE, related_name='vecinos_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Vecino')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('localidad', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localidad')),
                ('telefono', models.CharField(blank=True, max_length=55, null=True, verbose_name='Telefono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('Tipo', models.CharField(choices=[['Seguridad', 'Seguridad'], ['Programas educativos', 'Programas educativos'], ['Eventos', 'Eventos'], ['Mejoras de infraestructura', 'Mejoras de infraestructura'], ['Comités de vecinos', 'Comités de vecinos'], ['Otros', 'Otros']], max_length=100, verbose_name='Tipo de noticia')),
                ('Descripcion', models.TextField(verbose_name='Descripcion')),
                ('Fecha', models.DateField(verbose_name='Fecha de publicación')),
                ('Imagen', models.ImageField(upload_to='images/noticias/', verbose_name='Imagen')),
                ('redactor', models.ForeignKey(limit_choices_to={'groups__name': 'directiva'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Redactor')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(blank=True, default=False, null=True, verbose_name='Presente')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntavecinos.actividades', verbose_name='Actividad')),
                ('vecino', models.ForeignKey(limit_choices_to={'groups__name': 'usuario'}, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL, verbose_name='Vecino')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
